// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS8zPaUerFo6oiCVltd1HCa4lC9FuV_n0',
    appId: '1:993242623022:web:88e61082c35a8d869483bf',
    messagingSenderId: '993242623022',
    projectId: 'brindersocial',
    authDomain: 'brindersocial.firebaseapp.com',
    storageBucket: 'brindersocial.appspot.com',
    measurementId: 'G-M36MF5SRES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_g-hFViPYMbbDT9xBCc-2HJZkYNPImDo',
    appId: '1:993242623022:android:1782bcb2bd834be39483bf',
    messagingSenderId: '993242623022',
    projectId: 'brindersocial',
    storageBucket: 'brindersocial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC59iYMiCGK6MnQT-Uiaa1HyjmY-KCTM2I',
    appId: '1:993242623022:ios:e9667579990753959483bf',
    messagingSenderId: '993242623022',
    projectId: 'brindersocial',
    storageBucket: 'brindersocial.appspot.com',
    iosClientId: '993242623022-55f80rau66qtjff033a9dhofl6nmlmpu.apps.googleusercontent.com',
    iosBundleId: 'com.aworldaway.brinder',
  );
}
